### ISSUE TITLE
Authentication failing with `auth_setup_default()`

### ISSUE THREAD

**Issue by ccamara** [ropensci/rtweet#756]
### Problem

I just installed rtweet v 1.1.0 in a new machine and I cannot authenticate. When I run `auth_setup_default()`  I get the following error:

> Error in httr::init_oauth1.0(endpoint, app, permission = permission, is_interactive = is_interactive, : Bad Request (HTTP 400).

### Expected behavior

Rtweet should authenticate using my twitter credentials from my logged account in default web browser.

### Reproduce the problem

1. Install latest rtweet version (`install.packages("rtweet", repos = 'https://ropensci.r-universe.dev')`) 
2. Authenticate running `rtweet::auth_setup_default()`

### rtweet version

``` r
## copy/paste output
packageVersion("rtweet")
```
‘1.1.0.9000’

### Session info

``` r
## copy/paste output
> sessionInfo()
R version 4.2.2 (2022-10-31)
Platform: aarch64-apple-darwin20 (64-bit)
Running under: macOS Ventura 13.1

Matrix products: default
LAPACK: /Library/Frameworks/R.framework/Versions/4.2-arm64/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.9          withr_2.5.0         digest_0.6.31       later_1.3.0         R6_2.5.1            magrittr_2.0.3     
 [7] httr_1.4.4          rlang_1.0.6         cli_3.6.0           curl_5.0.0          rstudioapi_0.14     promises_1.2.0.1   
[13] rtweet_1.1.0.9000   xaringanExtra_0.7.0 tools_4.2.2         htmlwidgets_1.6.1   httpuv_1.6.8        xfun_0.36          
[19] fastmap_1.1.0       compiler_4.2.2      askpass_1.1         htmltools_0.5.4     openssl_2.0.5       knitr_1.41         
> 
```

**Comment by ccamara** [comment]
Not sure if this is an issue related to the package or the API itself, as it has been reported to fail in some cases (https://www.theverge.com/2023/1/13/23553161/third-party-twitter-clients-apps-outage-twitterific-tweetbot).

**Comment by llrs** [comment]
I have noticed some problems with some endpoints lately, but a couple of days ago I could authenticate without problems. I'll try again and let you know, but I think this is a problem from Twitter not the package. 

But I have been experiencing some problems with the authentication mechanism, so I will be monitoring/checking them more closely for a while. Thanks for reporting it.

**Comment by llrs** [comment]
For anyone with this same problem: Some users have reported that they could authenticate without problems via `rtweet_app` after obtaining their own credentials. This requires you, the user, to ask for developer access in order to obtain the bearer token but your credentials won't be tied to rtweet tokens.

**Comment by macmac4528** [comment]
Hi, ive been having this same problem (Bad Request HTTP 400). I just got developer access (essential level) and still have the same problem. I've even ran the rtweet_app() code and entered my bearer token.

Are there any additional steps to authenticating the twitter account in R other than running auth_setup_default()? If so, what are the R codes needed?

Sorry i am very new to pulling twitter data and R in general as I am a student in an analytics class. Your help would be greatly appreciated!

**Comment by llrs** [comment]
@macmac4528 Sorry to hear you have problems with rtweet. However, this is not the place to ask for help as this is to report if there are bugs with the package (which from your comment I don't think there is any). 

If you have questions, please ask at the [rOpenSci forum](https://discuss.ropensci.org/tag/rtweet) with exactly the code run in the same order (this is known as reproducible example and there are helpers to get it done such as [reprex](https://cran.r-project.org/package=reprex)), it will help me help you. I'm not sure if you have read the [authentication vignette](https://docs.ropensci.org/rtweet/articles/auth.html) but sharing what you tried (as you did here) and what have you read will help too. Good luck!

**Comment by llrs** [comment]
Mmh, it seems that while working in #744 I introduced an error that slipped through the checks into the release. Apologies!
This should now be fixed in devel in version 1.1.0.9001: `install.packages("rtweet", repos = 'https://ropensci.r-universe.dev/')` or `remotes::install_github("ropensci/rtweet")`. I'll try to make a new release soon.

**Comment by ratnanil** [comment]
https://github.com/ropensci/rtweet/issues/756#issuecomment-1401069647 solved the issue for me!

**Comment by llrs** [comment]
Thanks for confirming it @ratnanil. I'll close the issue now (but I'll pin it for users of current release)

**Comment by flxmrtn** [comment]
"> Mmh, it seems that while working in #744 I introduced an error that slipped through the checks into the release. Apologies!
> This should now be fixed in devel in version 1.1.0.9001: `install.packages("rtweet", repos = 'https://ropensci.r-universe.dev/')` or `remotes::install_github("ropensci/rtweet")`. I'll try to make a new release soon."



Hello, if I do this, it works for one time. Afterward, I have to install the package again, restart Rstudio, and repeat it for the next Account. With the remotes::install it works without restarting, but I still have to repeat the installation. As I want to pull tweets from 1500 accounts, I would like to do it with a for loop, but that is not working for me with installing the package inside the loop. 
That's my loop, maybe someone can help me. 

`
big_tml = list()
tml = data.frame()
user = vector()

for (i in length(df$screen_name)){
tml<-get_timeline(df$scree_name[i], n=500, auth_setup_default())
user<-as.character(df$scree_name[i])

tml<- cbind(tml,user)
big_tml<-rbind(big_tml,tml)
}`

**Comment by flxmrtn** [comment]
Sorry I was to fast, thats my first time.
following, my try of a loop with including installation and authentication etc. which does not solve the problem for me.

`for (i in 1:length(df$screen_name2)){
  
  remotes::install_github("ropensci/rtweet", force = TRUE)
  library("rtweet", "twitteR", "httr")
  df <- read.csv("Data_politicians.csv", sep = ";")
  df <- dplyr::select(politicians,c("lastname", "firstname", "gender", "state", "id", "party", "screen_name1", "user_id1"))
  df <- df[-which(is.na(df$user_id1)),]
  df$screen_name2 <- paste0("@",df$screen_name1)
  
  
  consumer_key <- "xxx"
  consumer_secret <- "xxx"
  access_token<- "xx-xx"
  access_secret <- "xx"
  
  setup_twitter_oauth(consumer_key ,consumer_secret, access_token, access_secret)

tml<-get_timeline(df$scree_name[i], n=500, auth_setup_default())

user<-as.character(df$scree_name[i])

tml<- cbind(tml,user)
big_tml<-rbind(big_tml,tml)
}`

**Comment by llrs** [comment]
@flxmrtn If you want to reuse a token you need to use `rtweet::auth_save` to save the token and `auth_as` to reuse them later on. 

You seem to use multiple packages. Please post your problem with the package to the original packge causing your issue or post your question in a public site if you have a question about how to use something.

**Comment by TCSMA** [comment]
The Authentication using auth_setup_default() is not working. After I installed the retweet using the development version, there is another error message when I run auth_setup_default(). 
Error in httr::init_oauth1.0(endpoint, app, permission = permission, is_interactive = is_interactive,  :   Unauthorized (HTTP 401).
Are there any ways to solve this problem? Thank you very much.

**Comment by llrs** [comment]
@TCSMA The error message seems to indicate you didn't authorize rtweet to access you account (401 Unauthorized). Maybe you weren't logged in Twitter. Are you sure there is a problem with rtweet? 

Did you in the browser get redirected to something like `http://127.0.0.1:1410/?oauth_token=m_qADFFDDSfdfdsafABhyosmoA&oauth_verifier=nLdfvDypho6Bafdasfd5WgfKdnbK0ixKSG`?

**Comment by TCSMA** [comment]
Thank you very much for your reply. I don't see any window that pops up for authentication. When I first install the rtweet in the development version, there was error about dependency and failed to install it. Then I install rtweet using the published version. Then I install the development version again. Then I got the error message.

**Comment by llrs** [comment]
Can you provide the output of `auth_sitrep()`?

**Comment by TCSMA** [comment]
When I first installed the development version of R, I cannot install it and got the following error message. This step worked on Monday afternoon and stopped working on Tuesday morning. 
> install.packages("rtweet", repos = 'https://ropensci.r-universe.dev/')
WARNING: Rtools is required to build R packages but is not currently installed. Please download and install the appropriate version of Rtools before proceeding:

https://cran.rstudio.com/bin/windows/Rtools/
Installing package into ‘C:/Users/CBS-HELAB2-09/Documents/R/win-library/4.1’
(as ‘lib’ is unspecified)
Warning in install.packages :
  dependencies ‘bit64’, ‘curl’, ‘httr’, ‘httr2’, ‘jsonlite’, ‘lifecycle’, ‘progress’, ‘rlang’, ‘tibble’, ‘withr’ are not available

  There is a binary version available but the source version is later:
           binary     source needs_compilation
rtweet 1.1.0.9001 1.1.0.9011             FALSE

installing the source package ‘rtweet’

trying URL 'https://ropensci.r-universe.dev/src/contrib/rtweet_1.1.0.9011.tar.gz'
Content type 'application/x-gzip' length 3349301 bytes (3.2 MB)
downloaded 3.2 MB

ERROR: dependencies 'bit64', 'curl', 'httr', 'httr2', 'jsonlite', 'lifecycle', 'progress', 'rlang', 'tibble', 'withr' are not available for package 'rtweet'
* removing 'C:/Users/CBS-HELAB2-09/Documents/R/win-library/4.1/rtweet'
Warning in install.packages :
  installation of package ‘rtweet’ had non-zero exit s

Then I installed the published version of rtweet, the installation is successful but cannot use auth_setup_default(). The error message is 
Error in httr::init_oauth1.0(endpoint, app, permission = permission, is_interactive = is_interactive,  : 
  Bad Request (HTTP 400).

Then I installed the development version of rtweet again. When I run auth_setup_default(), the error message is 
> auth_setup_default()
Error in httr::init_oauth1.0(endpoint, app, permission = permission, is_interactive = is_interactive,  : 
  Unauthorized (HTTP 401).
> auth_sitrep()
> 
There is no output if I use auth_sitrep()
Thank you so much!

**Comment by llrs** [comment]
When you tried to install from r-universe it told you that the binaries are outdated. When trying to install from source you can't because you don't have Rtools installed. To install RTools you'll need to know the R version and install it from [its website](https://cran.r-project.org/bin/windows/Rtools/). 
 
It seems that you don't have loaded rtweet and so auth_sitrep didn't work. Try again with `rtweet::auth_sitrep()` or first loading the package: `library("rtweet")`.

So far I haven't seen any evidence that rtweet is failing with rtweet version 1.1.0.9001 or 1.1.0.9011. Please let me know when you have some problems with version 1.1.0.9011 or later. Thanks!

**Comment by TCSMA** [comment]
Thanks a lot! I installed the RTools and reinstall rtweet development version. I successfully installed the version but I still get the same error. It seems that rtweet_user() function returns this error. Error in httr::init_oauth1.0(endpoint, app, permission = permission, is_interactive = is_interactive, :
Unauthorized (HTTP 401).

**Comment by llrs** [comment]
@TCSMA Please provide the rtweet version you are using and the output of `rtweet::auth_sitrep()`, also please provide the full message you get in your terminal and the `traceback()` after the error. Without it I can only make wild guesses.

**Comment by TCSMA** [comment]
Thank you very much for helping.
The rtweet version is  rtweet_1.1.0.9011
auth_sitrep() and rtweet::auth_sitrep() returned nothing. 

> auth_sitrep()
> rtweet::auth_sitrep()
> traceback()
9: stop(http_condition(x, "error", task = task, call = call))
8: stop_for_status(response)
7: httr::init_oauth1.0(endpoint, app, permission = permission, is_interactive = is_interactive, 
       private_key = private_key)
6: twitter_init_oauth1.0(self$endpoint, self$app, permission = self$params$permission, 
       private_key = self$private_key)
5: self$init_credentials()
4: initialize(...)
3: TwitterToken1.0$new(app = app, endpoint = httr::oauth_endpoints("twitter"), 
       params = list(as_header = TRUE), cache_path = FALSE)
2: rtweet_user()
1: auth_setup_default()

**Comment by llrs** [comment]
Sorry, this can be the new Twitter policy regarding the API or something else (that you need elevated access or something). You will have to debug this issue further for me to see if I need to fix something.

**Comment by llrs** [comment]
@azadesel You have duplicated tokens but don't seem to have saved bearer tokens (from your academic access) or the default token.
If you set up your academic access via the bearer token you don't need to run `auth_setup_default()`. 

You also seem to be using rtweet 1.1.0 with the bug that started this issue. Please install the devel version from github where this is fixed.

**Comment by llrs** [comment]
Ok, @azadesel it seem you introduce your token but you don't save or use it for each function. 
Please carefully [read the vignette about authorization](https://docs.ropensci.org/rtweet/articles/auth.html#default), for easier access you should:

```r
library("rtweet")
token <- rtwet_app()
auth_as(token)
auth_save(token, "academic_token")
su <- search_users("#rstats", n = 200)
```

In a fresh session then you can do this:

```r
library("rtweet")
auth_as(token, "academic_token")
su <- search_users("#rstats", n = 200)
```

**Comment by TCSMA** [comment]
@llrs . Thank you very much for your help. I also saw the developer portal interface changed as well.
